// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoogleClass.Migrations
{
    [DbContext(typeof(GcDbContext))]
    [Migration("20260616103055_PeerToPeerGrading")]
    partial class PeerToPeerGrading
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Criteria.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriterionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Criteria");

                    b.HasDiscriminator<string>("CriterionType").HasValue("Criterion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Criteria.ToggledCriterionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EvaluatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSelfAssessment")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PeerReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamSolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("EvaluatorUserId");

                    b.HasIndex("PeerReviewId");

                    b.HasIndex("SolutionId");

                    b.HasIndex("TeamSolutionId");

                    b.ToTable("ToggledCriterionValues");
                });

            modelBuilder.Entity("Domain.Models.Criteria.WeightedCriterionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSelfAssessment")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PeerReviewId")
                        .HasColumnType("uuid");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamSolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("EvaluatorUserId");

                    b.HasIndex("PeerReviewId");

                    b.HasIndex("SolutionId");

                    b.HasIndex("TeamSolutionId");

                    b.ToTable("WeightedCriterionValues");
                });

            modelBuilder.Entity("Domain.Models.Domain.Models.CaptainVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VoterId");

                    b.ToTable("CaptainVotes");
                });

            modelBuilder.Entity("Domain.Models.FileTeamSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamSolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TeamSolutionId");

                    b.ToTable("FileTeamSolutions");
                });

            modelBuilder.Entity("Domain.Models.GradeDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustomized")
                        .HasColumnType("boolean");

                    b.Property<long>("RawScore")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("TeamId");

                    b.ToTable("GradeDistributions");
                });

            modelBuilder.Entity("Domain.Models.GradeDistributionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DistributionId");

                    b.HasIndex("UserId");

                    b.ToTable("GradeDistributionEntries");
                });

            modelBuilder.Entity("Domain.Models.GradeDistributionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistributionId");

                    b.HasIndex("UserId");

                    b.ToTable("GradeDistributionVotes");
                });

            modelBuilder.Entity("Domain.Models.PeerReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReviewerTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamSolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ReviewerTeamId");

                    b.HasIndex("SolutionId");

                    b.HasIndex("TeamSolutionId");

                    b.HasIndex("TaskId", "ReviewerId", "SolutionId")
                        .IsUnique();

                    b.HasIndex("TaskId", "ReviewerId", "TeamSolutionId")
                        .IsUnique();

                    b.ToTable("PeerReviews");
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GoogleClass.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentableId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommentableId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GoogleClass.Models.Commentable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Commentable");

                    b.HasDiscriminator().HasValue("Commentable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GoogleClass.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GoogleClass.Models.CourseRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseRoles");
                });

            modelBuilder.Entity("GoogleClass.Models.FilePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("PostId");

                    b.ToTable("FilePosts");
                });

            modelBuilder.Entity("GoogleClass.Models.FileSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("SolutionId");

                    b.ToTable("FileSolutions");
                });

            modelBuilder.Entity("GoogleClass.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FixedCaptainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GoogleClass.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("GoogleClass.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GoogleClass.Models.UserFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Criteria.QualityCoefficient", b =>
                {
                    b.HasBaseType("Domain.Models.Criteria.Criterion");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<float>("Threshold")
                        .HasColumnType("real");

                    b.ToTable("Criteria", t =>
                        {
                            t.Property("Direction")
                                .HasColumnName("QualityCoefficient_Direction");

                            t.Property("Score")
                                .HasColumnName("QualityCoefficient_Score");
                        });

                    b.HasDiscriminator().HasValue("Quality");
                });

            modelBuilder.Entity("Domain.Models.Criteria.ToggledCriterion", b =>
                {
                    b.HasBaseType("Domain.Models.Criteria.Criterion");

                    b.HasDiscriminator().HasValue("ToggledCriterion");
                });

            modelBuilder.Entity("Domain.Models.Criteria.WeightedCriterion", b =>
                {
                    b.HasBaseType("Domain.Models.Criteria.Criterion");

                    b.Property<float>("MaxScore")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Weighted");
                });

            modelBuilder.Entity("Domain.Models.TeamSolution", b =>
                {
                    b.HasBaseType("GoogleClass.Models.Commentable");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TeamId");

                    b.ToTable("Commentable", t =>
                        {
                            t.Property("Text")
                                .HasColumnName("TeamSolution_Text");
                        });

                    b.HasDiscriminator().HasValue("TeamSolution");
                });

            modelBuilder.Entity("GoogleClass.Models.GenericPost", b =>
                {
                    b.HasBaseType("GoogleClass.Models.Commentable");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("GenericPost");
                });

            modelBuilder.Entity("GoogleClass.Models.Solution", b =>
                {
                    b.HasBaseType("GoogleClass.Models.Commentable");

                    b.Property<bool>("PeerReviewCounted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Commentable", t =>
                        {
                            t.Property("Score")
                                .HasColumnName("Solution_Score");

                            t.Property("Status")
                                .HasColumnName("Solution_Status");

                            t.Property("SubmittedAt")
                                .HasColumnName("Solution_SubmittedAt");

                            t.Property("TaskId")
                                .HasColumnName("Solution_TaskId");

                            t.Property("Text")
                                .HasColumnName("Solution_Text");
                        });

                    b.HasDiscriminator().HasValue("Solution");
                });

            modelBuilder.Entity("Domain.Models.Criteria.BlockingModifier", b =>
                {
                    b.HasBaseType("Domain.Models.Criteria.ToggledCriterion");

                    b.Property<float>("MaxAllowedScore")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Blocking");
                });

            modelBuilder.Entity("Domain.Models.Criteria.BonusPenaltyCriterion", b =>
                {
                    b.HasBaseType("Domain.Models.Criteria.ToggledCriterion");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("BonusPenalty");
                });

            modelBuilder.Entity("Domain.Models.RegularPost", b =>
                {
                    b.HasBaseType("GoogleClass.Models.GenericPost");

                    b.HasDiscriminator().HasValue("RegularPost");
                });

            modelBuilder.Entity("Domain.Models.TeamAssignment", b =>
                {
                    b.HasBaseType("GoogleClass.Models.GenericPost");

                    b.Property<bool>("AllowJoinTeam")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowLeaveTeam")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowStudentTransferCaptain")
                        .HasColumnType("boolean");

                    b.Property<int>("CaptainMode")
                        .HasColumnType("integer");

                    b.Property<bool>("CopyGroupsFromPreviousAssignment")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("FailThreshold")
                        .HasColumnType("real");

                    b.Property<Guid?>("FixedCaptainId")
                        .HasColumnType("uuid");

                    b.Property<int>("GradingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxDays")
                        .HasColumnType("integer");

                    b.Property<long>("MaxScore")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxTeamSize")
                        .HasColumnType("integer");

                    b.Property<int>("MinTeamSize")
                        .HasColumnType("integer");

                    b.Property<float?>("PenaltyPerDay")
                        .HasColumnType("real");

                    b.Property<int>("PredefinedTeamsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SolvableAfterDeadline")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SourceAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<float>("StudentScoreWeight")
                        .HasColumnType("real");

                    b.Property<float?>("SuccessThreshold")
                        .HasColumnType("real");

                    b.Property<int?>("VotingDurationHours")
                        .HasColumnType("integer");

                    b.ToTable("Commentable", t =>
                        {
                            t.Property("Deadline")
                                .HasColumnName("TeamAssignment_Deadline");

                            t.Property("FailThreshold")
                                .HasColumnName("TeamAssignment_FailThreshold");

                            t.Property("GradingMode")
                                .HasColumnName("TeamAssignment_GradingMode");

                            t.Property("MaxDays")
                                .HasColumnName("TeamAssignment_MaxDays");

                            t.Property("MaxScore")
                                .HasColumnName("TeamAssignment_MaxScore");

                            t.Property("PenaltyPerDay")
                                .HasColumnName("TeamAssignment_PenaltyPerDay");

                            t.Property("SolvableAfterDeadline")
                                .HasColumnName("TeamAssignment_SolvableAfterDeadline");

                            t.Property("StudentScoreWeight")
                                .HasColumnName("TeamAssignment_StudentScoreWeight");

                            t.Property("SuccessThreshold")
                                .HasColumnName("TeamAssignment_SuccessThreshold");
                        });

                    b.HasDiscriminator().HasValue("TeamAssignment");
                });

            modelBuilder.Entity("GoogleClass.Models.Assignment", b =>
                {
                    b.HasBaseType("GoogleClass.Models.GenericPost");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("FailThreshold")
                        .HasColumnType("real");

                    b.Property<int>("GradingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxDays")
                        .HasColumnType("integer");

                    b.Property<long>("MaxScore")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinPeerReviewsRequired")
                        .HasColumnType("integer");

                    b.Property<float?>("PenaltyPerDay")
                        .HasColumnType("real");

                    b.Property<bool>("SolvableAfterDeadline")
                        .HasColumnType("boolean");

                    b.Property<float>("StudentScoreWeight")
                        .HasColumnType("real");

                    b.Property<float?>("SuccessThreshold")
                        .HasColumnType("real");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Assignment");
                });

            modelBuilder.Entity("Domain.Models.Criteria.Criterion", b =>
                {
                    b.HasOne("GoogleClass.Models.GenericPost", "Post")
                        .WithMany("Criteria")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.Models.Criteria.ToggledCriterionValue", b =>
                {
                    b.HasOne("Domain.Models.Criteria.ToggledCriterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.PeerReview", "PeerReview")
                        .WithMany("ToggledValues")
                        .HasForeignKey("PeerReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoogleClass.Models.Solution", "Solution")
                        .WithMany("ToggledValues")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.TeamSolution", "TeamSolution")
                        .WithMany("ToggledValues")
                        .HasForeignKey("TeamSolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Criterion");

                    b.Navigation("Evaluator");

                    b.Navigation("PeerReview");

                    b.Navigation("Solution");

                    b.Navigation("TeamSolution");
                });

            modelBuilder.Entity("Domain.Models.Criteria.WeightedCriterionValue", b =>
                {
                    b.HasOne("Domain.Models.Criteria.WeightedCriterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.PeerReview", "PeerReview")
                        .WithMany("WeightedValues")
                        .HasForeignKey("PeerReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoogleClass.Models.Solution", "Solution")
                        .WithMany("WeightedValues")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.TeamSolution", "TeamSolution")
                        .WithMany("WeightedValues")
                        .HasForeignKey("TeamSolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Criterion");

                    b.Navigation("Evaluator");

                    b.Navigation("PeerReview");

                    b.Navigation("Solution");

                    b.Navigation("TeamSolution");
                });

            modelBuilder.Entity("Domain.Models.Domain.Models.CaptainVote", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Team");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Domain.Models.FileTeamSolution", b =>
                {
                    b.HasOne("GoogleClass.Models.UserFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TeamSolution", "TeamSolution")
                        .WithMany("FileTeamSolutions")
                        .HasForeignKey("TeamSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("TeamSolution");
                });

            modelBuilder.Entity("Domain.Models.GradeDistribution", b =>
                {
                    b.HasOne("Domain.Models.TeamAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Models.GradeDistributionEntry", b =>
                {
                    b.HasOne("Domain.Models.GradeDistribution", "Distribution")
                        .WithMany("Entries")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.GradeDistributionVote", b =>
                {
                    b.HasOne("Domain.Models.GradeDistribution", "Distribution")
                        .WithMany("Votes")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.PeerReview", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Team", "ReviewerTeam")
                        .WithMany()
                        .HasForeignKey("ReviewerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoogleClass.Models.Solution", "Solution")
                        .WithMany()
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoogleClass.Models.GenericPost", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TeamSolution", "TeamSolution")
                        .WithMany()
                        .HasForeignKey("TeamSolutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reviewer");

                    b.Navigation("ReviewerTeam");

                    b.Navigation("Solution");

                    b.Navigation("Task");

                    b.Navigation("TeamSolution");
                });

            modelBuilder.Entity("GoogleClass.Models.Comment", b =>
                {
                    b.HasOne("GoogleClass.Models.Commentable", "Commentable")
                        .WithMany("Comments")
                        .HasForeignKey("CommentableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentable");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoogleClass.Models.Course", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GoogleClass.Models.CourseRole", b =>
                {
                    b.HasOne("GoogleClass.Models.Course", "Course")
                        .WithMany("CourseRoles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoogleClass.Models.FilePost", b =>
                {
                    b.HasOne("GoogleClass.Models.UserFile", "File")
                        .WithMany("FilePosts")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.GenericPost", "Post")
                        .WithMany("FilePosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("GoogleClass.Models.FileSolution", b =>
                {
                    b.HasOne("GoogleClass.Models.UserFile", "File")
                        .WithMany("FileSolutions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Solution", "Solution")
                        .WithMany("FileSolutions")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("GoogleClass.Models.Team", b =>
                {
                    b.HasOne("Domain.Models.TeamAssignment", "Assignment")
                        .WithMany("Teams")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GoogleClass.Models.TeamMember", b =>
                {
                    b.HasOne("GoogleClass.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoogleClass.Models.UserFile", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GoogleClass.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GoogleClass.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GoogleClass.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.TeamSolution", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TeamAssignment", "Task")
                        .WithMany("TeamSolutions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Team", "Team")
                        .WithMany("TeamSolutions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedByUser");

                    b.Navigation("Task");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GoogleClass.Models.GenericPost", b =>
                {
                    b.HasOne("GoogleClass.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoogleClass.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GoogleClass.Models.Solution", b =>
                {
                    b.HasOne("GoogleClass.Models.Assignment", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.HasOne("GoogleClass.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.GradeDistribution", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Domain.Models.PeerReview", b =>
                {
                    b.Navigation("ToggledValues");

                    b.Navigation("WeightedValues");
                });

            modelBuilder.Entity("GoogleClass.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GoogleClass.Models.Commentable", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("GoogleClass.Models.Course", b =>
                {
                    b.Navigation("CourseRoles");
                });

            modelBuilder.Entity("GoogleClass.Models.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TeamSolutions");
                });

            modelBuilder.Entity("GoogleClass.Models.UserFile", b =>
                {
                    b.Navigation("FilePosts");

                    b.Navigation("FileSolutions");
                });

            modelBuilder.Entity("Domain.Models.TeamSolution", b =>
                {
                    b.Navigation("FileTeamSolutions");

                    b.Navigation("ToggledValues");

                    b.Navigation("WeightedValues");
                });

            modelBuilder.Entity("GoogleClass.Models.GenericPost", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("FilePosts");
                });

            modelBuilder.Entity("GoogleClass.Models.Solution", b =>
                {
                    b.Navigation("FileSolutions");

                    b.Navigation("ToggledValues");

                    b.Navigation("WeightedValues");
                });

            modelBuilder.Entity("Domain.Models.TeamAssignment", b =>
                {
                    b.Navigation("TeamSolutions");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
